---
- hosts: kitchen
  tasks:
    - name: Configure Kitchen and Vagrant
      include_role:
        name: kitchen-support
    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present
    - name: add vagrant user to docker group
      user:
        name: vagrant
        append: yes
        groups:
        - docker

- hosts: all
  tasks:
    - name: Add repos
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - "deb http://deb.debian.org/debian buster main contrib non-free"
        - "deb-src http://deb.debian.org/debian buster main contrib non-free"
        - "deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free"
        - "deb-src http://deb.debian.org/debian-security/ buster/updates main contrib non-free"
        - "deb http://deb.debian.org/debian buster-updates main contrib non-free"
        - "deb-src http://deb.debian.org/debian buster-updates main contrib non-free"
        - "deb http://deb.debian.org/debian buster-backports main contrib non-free"
        - "deb-src http://deb.debian.org/debian buster-backports main contrib non-free"
    - name: Update APT and upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install Docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: true
    - name: Configure Gnome, NX, and OBS
      include_role:
        name: devday-regie
